(function(){
  var selectedTool='Music';
  var toolPrompts={Music:'Cinematic launch cue with a restrained electronic pulse, evolving harmony, and a decisive final lift.',SFX:'Layered urban ambience with distant transit, soft rain, and restrained human activity.',Narration:'Calm, precise product narration with measured pacing and a warm but neutral delivery.',Agents:'Helpful voice concierge that confirms intent, summarizes next steps, and stops before consequential actions.',Voices:'Versatile studio voice profile with clear consonants, natural pauses, and consistent emotional range.'};
  var abbreviations={Music:'MU',SFX:'FX',Narration:'NR',Agents:'AG',Voices:'VO'};
  var toast=document.querySelector('[data-toast]');
  var recent=document.querySelector('[data-recent]');
  function show(message){toast.textContent=message;toast.classList.add('visible');setTimeout(function(){toast.classList.remove('visible')},3000)}
  function selectTool(tool){selectedTool=tool;document.querySelectorAll('[data-tool]').forEach(function(node){node.classList.toggle('active',node.getAttribute('data-tool')===tool)});document.querySelector('[data-selected-label]').textContent=tool+' selected';document.querySelector('[data-composer-title]').textContent=tool+' brief';document.querySelector('[data-prompt]').value=toolPrompts[tool]||'';}
  function updateCount(){var visible=[].slice.call(recent.querySelectorAll('.creation')).filter(function(item){return item.style.display!=='none'}).length;document.querySelector('[data-count]').textContent=visible+(visible===1?' item':' items')}
  document.addEventListener('click',function(event){var target=event.target;if(!(target instanceof Element))return;var tool=target.closest('[data-tool]');if(tool){selectTool(tool.getAttribute('data-tool'));return}var action=target.closest('[data-action]');if(!action)return;var name=action.getAttribute('data-action');if(name==='clear'){document.querySelector('[data-prompt]').value='';show('Brief cleared locally.')}if(name==='new'){selectTool('Music');document.querySelector('[data-duration]').value='60 seconds';show('New review project started.')}if(name==='play'){var wave=document.querySelector('[data-wave]');wave.classList.toggle('playing');action.textContent=wave.classList.contains('playing')?'Pause waveform animation':'Play waveform animation'}if(name==='generate'){var prompt=document.querySelector('[data-prompt]').value.trim();if(!prompt){show('Add a generation brief before creating a preview.');return}action.disabled=true;action.textContent='Creating…';setTimeout(function(){var title=selectedTool+' Review '+String(recent.children.length+1).padStart(2,'0');var item=document.createElement('div');item.className='creation';item.setAttribute('data-name',title);item.innerHTML='<span class="creation-art">'+abbreviations[selectedTool]+'</span><div><strong>'+title+'</strong><small>'+selectedTool+' · browser-local preview</small></div><time>0:60</time>';recent.insertBefore(item,recent.firstChild);document.querySelector('[data-now-playing]').textContent=title;updateCount();show('Local '+selectedTool+' preview created. No provider call was made.');action.disabled=false;action.textContent='Generate review preview'},650)}});
  document.querySelector('[data-search]').addEventListener('input',function(event){var query=event.target.value.toLowerCase();recent.querySelectorAll('.creation').forEach(function(item){item.style.display=(item.getAttribute('data-name')||'').toLowerCase().includes(query)?'grid':'none'});updateCount()});
  updateCount();
}());
